package com.mycompany.erwthsh_12;    
 // author Evangelos Kapsoulakis
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.xml.XMLConstants;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.stream.StreamSource;
import javax.xml.validation.SchemaFactory;
import org.w3c.dom.NamedNodeMap;
public class main extends javax.swing.JFrame {
    
       
       
       
    /**
     * Creates new form main
     */
    public main() {
		initComponents();
	//prosthetoyme th paraskevi kai all days epiloges	     
        jComboBox1.addItem("Friday");
        jComboBox1.addItem("All Days");
        
        //default model gia to pinaka
        DefaultTableModel tblModel = (DefaultTableModel)xmltable.getModel();
        //metavliti tou profesor name pou pernoyme apo to xml
        String professor;
   
        
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
      
        try {

                DocumentBuilder builder = factory.newDocumentBuilder();

                
                Document document = builder.parse(new File("12_schedule.xml"));

             
                document.getDocumentElement().normalize();

                
                Element root = document.getDocumentElement();

                //lista me ta elements lesson
                NodeList node_list = document.getElementsByTagName("Lesson");
                //benoume mesa sth lista
                for (int temp = 0; temp < node_list.getLength(); temp++){
                    Node node = node_list.item(temp);
                    
                            
                   if (node.getNodeType() == Node.ELEMENT_NODE  )
                   {
                       
                        Element element = (Element) node;
                        //elegxos ama to lesson exei element professor h oxi.
                       if (element.getElementsByTagName("Professor").item(0)== null){
                            professor = "";
                      
                       }else{
                             professor = element.getElementsByTagName("Professor").item(0).getTextContent();
                         
                       }
                       
                       //pernoyme olous tous titlous twn lesson kai ta days
                        String title = element.getElementsByTagName("Title").item(0).getTextContent();
                        String day = element.getElementsByTagName("Day").item(0).getTextContent();
                        
                        //data pou pirame apo to xml gia na ta valoume sto pinaka
                        String xml_data[] = {title,professor,day};
                        
                        tblModel.addRow(xml_data);
                   }
                } 

 
        
        } catch (ParserConfigurationException | SAXException | IOException e) {
          e.printStackTrace();
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        xmltable = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        title_txt = new javax.swing.JTextField();
        professor_txt = new javax.swing.JTextField();
        day_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        time_txt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        xmltable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Professor", "Day"
            }
        ));
        jScrollPane1.setViewportView(xmltable);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        title_txt.setText("title");

        professor_txt.setText("professor");

        day_txt.setText("day");
        day_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day_txtActionPerformed(evt);
            }
        });

        jButton1.setText("add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        time_txt.setText("time");

        jButton2.setText("validate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title_txt)
                            .addComponent(professor_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(day_txt)
                            .addComponent(time_txt))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(21, 21, 21)
                        .addComponent(title_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(day_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(time_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(professor_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//
    //sinartisi poy  filtrarei ton pinaka me vasi mias timis
    private void filter (String query){
        DefaultTableModel tblMode2 = (DefaultTableModel)xmltable.getModel();
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(tblMode2);
        xmltable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
    
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      //analoga th mera emfanizi ta stoixia tou xml
        String selectedValue = jComboBox1.getSelectedItem().toString();
       //kalesma filter sinartisis
        String query = selectedValue;
        filter(query);
        //ama to all days epilextei ksanagemizi o pinakas
        if (selectedValue == "All Days") {
                DefaultTableModel tableModel = (DefaultTableModel) xmltable.getModel();
             tableModel.setRowCount(0);
               String professor;
        
   
             
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
      
        try {

                DocumentBuilder builder = factory.newDocumentBuilder();

               
                Document document = builder.parse(new File("12_schedule.xml"));

         
                document.getDocumentElement().normalize();

                
                Element root = document.getDocumentElement();

                NodeList nList = document.getElementsByTagName("Day");
                NodeList nList2 = document.getElementsByTagName("Lecture");
                NodeList nList3 = document.getElementsByTagName("Lesson");
                for (int temp = 0; temp < nList3.getLength(); temp++){
                    Node node = nList3.item(temp);
                    
                            
                   if (node.getNodeType() == Node.ELEMENT_NODE  )
                   {
                       
                        Element element = (Element) node;
                        
                       if (element.getElementsByTagName("Professor").item(0)== null){
                            professor = "";
                      
                       }else{
                             professor = element.getElementsByTagName("Professor").item(0).getTextContent();
                         
                       }
                       

                        String title = element.getElementsByTagName("Title").item(0).getTextContent();
                        String day = element.getElementsByTagName("Day").item(0).getTextContent();
                    
                        String xml_data[] = {title,professor,day};
                        
                        tableModel.addRow(xml_data);
                        xmltable.repaint();
                   }
                } 

 
        
        } catch (ParserConfigurationException | SAXException | IOException e) {
          e.printStackTrace();
      }
        tableModel.fireTableDataChanged();
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(tableModel);
        xmltable.setRowSorter(tr);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void day_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_day_txtActionPerformed
// dimiourgia neou Lesson element vasi ton text values
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            //pernoyme tis times ton text box
            String titletext = title_txt.getText();
            String daytext = day_txt.getText().toString();
            String timetext = time_txt.getText().toString();
            String proftext = professor_txt.getText().toString();

       
            try {
                DocumentBuilder db = dbf.newDocumentBuilder();
                Document document = db.parse("12_schedule.xml");
                //1o append mesa sto root element gia na valoyme to Lesson
                Element root = document.getDocumentElement();
                Element lesson = document.createElement("Lesson");
                root.appendChild(lesson);
                //2o append mesa sto lesson gia na valoyme to title
                Element title = document.createElement("Title");
                title.appendChild(document.createTextNode(titletext));
                lesson.appendChild(title);

                //3o append mesa sto lesson gia na valoyme to lecture
                Element lecture = document.createElement("Lecture");
                lesson.appendChild(lecture);
                //4o append mesa sto lecture gia na valoyme to day
                Element day = document.createElement("Day");
                day.appendChild(document.createTextNode(daytext));
                lecture.appendChild(day);
                //5o append mesa sto lecture gia na valoyme to time
                Element time = document.createElement("Time");
                time.appendChild(document.createTextNode(timetext));
                lecture.appendChild(time);
                //6o append mesa sto lesson gia na valoyme to proffesor
                Element professor = document.createElement("Professor");
                professor.appendChild(document.createTextNode(proftext));
                lesson.appendChild(professor);                
                //"update" tou xml arxeiou
                TransformerFactory factory = TransformerFactory.newInstance();
                Transformer transformer = factory.newTransformer();
                DOMSource domSource = new DOMSource(document);
                StreamResult streamResult = new StreamResult(new File("12_schedule.xml"));
                transformer.transform(domSource, streamResult);

                DOMSource source = new DOMSource(document);
         
            } catch (SAXException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParserConfigurationException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            } catch (TransformerException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            //validation check me to xsd arxeio
            // on succes emfanizi no error
            // on failure emfanizi to xml error
            boolean flag = false;
            try {              
                validate("12_schedule.xml","12_schedule.xsd");
                flag = true;
                JOptionPane.showMessageDialog(null,"xml validated with no error!");
            }
            catch(SAXException ex){
                flag=false;
                JOptionPane.showMessageDialog(null,ex);
            }
            catch(IOException ex){
                flag=false;
                JOptionPane.showMessageDialog(null,ex);}
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public static void validate(String xmlFile,String validationFile) throws SAXException, IOException{
    
        SchemaFactory schemaFactory = SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);
        ((schemaFactory.newSchema(new File(validationFile))).newValidator()).validate(new StreamSource(new File(xmlFile)));
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField day_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField professor_txt;
    private javax.swing.JTextField time_txt;
    private javax.swing.JTextField title_txt;
    private javax.swing.JTable xmltable;
    // End of variables declaration//GEN-END:variables
}
